project:
  type: website
sidebar:
  logo: SS4S.key.png
website:
  title: "Social Science for Sustainability — Course Notes"
  navbar:
    right:
      - text: "Subscribe to SS4S"
        href: "https://matphd.substack.com"
      - text: "Return to SS4S Home"
        href: https://SocSci-for-Sustainability.github.io/
    
    collapse: true
    pinned: true
    search: true

bibliography: 
  - /Users/mt/workspace/Writing/library.bib
  - references.bib

format:
  html:
    toc: true
    include-in-header: header.html
    theme: 
      light:
        - theme-light.scss
        - styles.scss
      dark:
        - darkly 
        - theme-dark.scss
        - styles.scss
    fontsize: 1.0em
    linestretch: 1.2
    number-sections: true
    number-depth: 3

